package com.example.board.domain.board;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.validation.constraints.NotEmpty;
import lombok.Data;

import java.time.LocalDateTime;

/*
create table comment
        (
        id bigint generated by default as identity,
        comment_content varchar(50),
        member_nickname varchar(20) not null,
        post_id bigint,
        date timestamp,
        primary key (id),
        foreign key (member_nickname) references member(nickname),
        foreign key (post_id) references post(id)
        );
*/

@Data
@Entity
public class Comment {

    @Id @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id; //댓글 id (PK)

    @NotEmpty
    private String commentContent; //내용
    private String memberNickname; //작성자 닉네임 (FK)
    private Long postId;  //작성글 id (FK)
    private LocalDateTime date;// 작성 시간

    public Comment() {
    }
}
