package com.example.board.domain.board;

import lombok.Data;

import java.time.LocalDateTime;

/**
 * create table board_
 *      (
 *          id bigint generated by default as identity,
 *          title varchar(50),
 *          content varchar(500),
 *          date timestamp,
 *          hits integer,
 *          primary key (post_id)
 *      );
 */

@Data
public class Post {

    private Long id; //글 id
    private String title; //글제목
    private String content; //글내용
    private LocalDateTime date; //날짜
    private int hits; //조회수

}
