package com.example.board.domain.board;

import lombok.Data;

import java.time.LocalDateTime;

/**
 * create table board_
 *      (
 *          post_id bigint generated by default as identity,
 *          post_title varchar(50),
 *          post_content varchar(500),
 *          post_date timestamp,
 *          post_hits integer,
 *          primary key (post_id)
 *      );
 */
@Data
public class Post {

    private Long postId; //글 id
    private String postTitle; //글제목
    private String postContent; //글내용
    private LocalDateTime postDate; //날짜
    private int postHits; //조회수

}
