package com.example.board.domain.board;

import lombok.Data;

import java.time.LocalDateTime;

/*
create table board_
     (
         id bigint generated by default as identity,
         title varchar(50),
         content varchar(500),
         date timestamp,
         hits integer,
         nickname varchar(20) not null,
         primary key (id),
         foreign key (nickname) references member(nickname)
     );
*/

@Data
public class Post {

    private Long id; //글 id (PK)
    private String title; //글제목
    private String content; //글내용
    private LocalDateTime date; //날짜
    private int hits; //조회수
    private String nickname; //글쓴이 Member.nickname (FK)
}
